M48
; DRILL file {KiCad 9.0.1} date 2025-05-06T09:48:11+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-06T09:48:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C8.400
%
G90
G05
T1
X90.75Y-56.5
X90.75Y-70.5
X144.75Y-56.5
X144.75Y-70.5
T2
X56.0Y-150.0
X181.0Y-150.0
M30
